### ISSUE TITLE
Feature Request: Customize Metadata (Example: Covers)

### ISSUE THREAD

**Issue by Novel-Idea** [daniel-j/fimfic2epub#1]
Custom covers would be top of the list for me for options. I always create custom covers for FiMFiction stories and I'd like to be able to directly embed them into the .EPUB. Having to add them in Sigil after the fact creates havoc in iBooks unless _very_ specific steps are taken. 

Implementation Suggestion: A feature in the Google Chrome Extension (such as a "Customize EPUB" checkbox) that gives a pop-up with the basic metadata if checked.

Here are the features I normally adjust:

- Tags - I always remove the My Little Pony & My Little Pony: Friendship is Magic tags, as they aren't required for me and they're so long that it makes any other tag impossible to read on an iOS device. 
- Cover (Both Large Cover and Small Cover) - Nyerguds's program only allows you to generate covers from web URLs. I don't know if you have this limitation or not, but being able to select a local file would be a nice touch, but the sheer amount of image hosting options out there, this is not required at all.

**Comment by daniel-j** [comment]
Implemented.
