### ISSUE TITLE
Downloading .EPUB from a Library Bookshelf Creates Default .EPUB

### ISSUE THREAD

**Issue by Novel-Idea** [daniel-j/fimfic2epub#13]
Steps to Reproduce:

1. Go to a user's bookshelf ([http://www.fimfiction.net/bookshelf/688586/the-top-shelf](http://www.fimfiction.net/bookshelf/688586/the-top-shelf)).
2. From this view, click the .EPUB button.
3. ---> The default .EPUB downloads instead of triggering the Chrome Extension.

**Comment by daniel-j** [comment]
I had this in mind but forgot XD
Right now the code only matches the button on story pages.

**Comment by daniel-j** [comment]
Fixed in 8f715c160a06a28db7b3816278c5eeeef16d51a4
