### ISSUE TITLE
Bug: Table of Contents Errors (No Page Numbers) causing failure to sync with Cloud-based iOS systems

### ISSUE THREAD

**Issue by Novel-Idea** [daniel-j/fimfic2epub#15]
I know I already brought this up, but I ran into a more serious problem (at least for me).

Story Used for the test: [http://www.fimfiction.net/story/8657/the-dresden-fillies-strange-friends](http://www.fimfiction.net/story/8657/the-dresden-fillies-strange-friends)

Symptom: 
**Page numbers are not being generated in iBooks for Mac OS X or iOS.** 
![screen shot 2016-09-12 at 8 58 08 am](https://cloud.githubusercontent.com/assets/21106478/18442842/20ad0708-78c7-11e6-9699-26f708ea9717.png)

Result:
**Notes, reading location, bookmarks and highlights are not syncing through iCloud to multiple devices (iOS or Mac OS).** 
Creating notes, reading location, bookmarks or highlights on an iPad will not sync to iPhone or Mac (or any combination of the three). I've tested this with multiple books, however, when I generated .EPUBs based on Nyerguds's EPUB Tool, they worked perfectly (as they had before).

Here's what I'm trying to figure out with the following data: 
Why does the Nyerguds Application work correctly with page numbers, table of contents as well as syncing notes, reading location, bookmarks and highlights while the Chrome Extension doesn't?

I hope to figure this out, because I constantly flip back and forth between my iPhone and my iPad. In addition, I often save notes and bookmarks for the various follow-ups I do. While there are workarounds for both issues, when the Nyerguds application supports this by default, it ends up being less time to just hop into Parallels and run that application to generate the EPUB than to use the Chrome Extension. 

I compared the generated files from both tools and here's what I've discovered:

**Djazz Application:**
Files are in XHTML format.
There is no toc.xhtml file by default. There is only a nav.xhtml - I tried simply changing this to toc.xhtml, but this had no effect. 

**Original nav.xhtml Table of Contents generated by Djazz Extension:**

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
<head>
    <meta charset="utf-8"/>
    <link rel="stylesheet" type="text/css" href="../Styles/style.css"/>
    <title>Contents</title>
  </head>
  <body id="navpage">
    <nav id="toc" epub:type="toc">
      <h3>Contents</h3>
      <ol>
        <li hidden="">
          <a href="../Text/cover.xhtml">Cover</a>
        </li>
        <li>
          <a href="../Text/chapter_001.xhtml" class="leftalign">Prologue</a>
        </li>
        <li>
          <a href="../Text/chapter_002.xhtml" class="leftalign">Chapter One</a>
        </li>
        <li>
          <a href="../Text/chapter_003.xhtml" class="leftalign">Chapter Two</a>
        </li>
        <li>
          <a href="../Text/chapter_004.xhtml" class="leftalign">Chapter Three</a>
        </li>
        <li>
          <a href="../Text/chapter_005.xhtml" class="leftalign">Chapter Four</a>
        </li>
        <li>
          <a href="../Text/chapter_006.xhtml" class="leftalign">Chapter Five</a>
        </li>
        <li>
          <a href="../Text/chapter_007.xhtml" class="leftalign">Chapter Six</a>
        </li>
        <li>
          <a href="../Text/chapter_008.xhtml" class="leftalign">Chapter Seven</a>
        </li>
        <li>
          <a href="../Text/chapter_009.xhtml" class="leftalign">Chapter Eight</a>
        </li>
        <li>
          <a href="../Text/chapter_010.xhtml" class="leftalign">Chapter Nine</a>
        </li>
        <li>
          <a href="../Text/chapter_011.xhtml" class="leftalign">Chapter Ten</a>
        </li>
        <li>
          <a href="../Text/chapter_012.xhtml" class="leftalign">Chapter Eleven</a>
        </li>
        <li>
          <a href="../Text/chapter_013.xhtml" class="leftalign">Chapter Twelve</a>
        </li>
      </ol>
    </nav>
</body>
</html>
```

When I open the file in Sigil and go to Tools -> Table of Contents -> "Create HTML Table of Contents," it replaces either nav.xhtml or toc.xhtml with the following data:

**HTML Table of Contents generated by Sigil from Djazz Extension:**

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" lang="en" xml:lang="en">
<head>
  <meta charset="utf-8" />
  <style type="text/css">
    nav#landmarks, nav#page-list { display:none; }
    ol { list-style-type: none; }
  </style>
</head>
<body epub:type="frontmatter">
  <nav epub:type="toc" id="toc">
  </nav>
  <nav epub:type="landmarks" id="landmarks" hidden="">
  </nav>
</body>
</html>
```

However, I should note that the "Generate Table of Contents" and "Edit Table of Contents" appear to work _before_ using the "Generate HTML Table of Contents," but they will not work after. 

**Nyerguds Application:**
Files are in HTML format.
When I open the file in Sigil and go to Tools -> Table of Contents -> "Create HTML Table of Contents," it creates a normal, functional table of contents.

**Original toc.html Table of Contents generated by Sigil from Nyerguds Application:**

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title>The Dresden Fillies: Strange Friends</title>
        <link rel="stylesheet" type="text/css" href="../Styles/style.css"/>
    </head>
    <body>
<div style="text-align:center"><h3>Table of Contents</h3>
</div>
<p class="double"><a href="../Text/ch0001_26220.html">Prologue</a>
</p>
<p><a href="../Text/ch0002_26223.html">Chapter One</a>
</p>
<p><a href="../Text/ch0003_26620.html">Chapter Two</a>
</p>
<p><a href="../Text/ch0004_26674.html">Chapter Three</a>
</p>
<p><a href="../Text/ch0005_26910.html">Chapter Four</a>
</p>
<p><a href="../Text/ch0006_27037.html">Chapter Five</a>
</p>
<p><a href="../Text/ch0007_27245.html">Chapter Six</a>
</p>
<p><a href="../Text/ch0008_27326.html">Chapter Seven</a>
</p>
<p><a href="../Text/ch0009_27670.html">Chapter Eight</a>
</p>
<p><a href="../Text/ch0010_27831.html">Chapter Nine</a>
</p>
<p><a href="../Text/ch0011_28028.html">Chapter Ten</a>
</p>
<p><a href="../Text/ch0012_28184.html">Chapter Eleven</a>
</p>
<p><a href="../Text/ch0013_28466.html">Chapter Twelve</a>
</p>
</body>
</html>
```

**HTML Table of Contents generated by Sigil from Nyerguds Application (Results in XHTML file: toc.xhtml):**

```
<?xml version="1.0"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
   "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Contents</title>
<link href="../Styles/sgc-toc.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<div class="sgc-toc-title">Table of Contents</div>
<div class="sgc-toc-level-1">
  <a href="../Text/title.html">Cover</a>
</div>
<div class="sgc-toc-level-1">
  <a href="../Text/synopsis.html">Synopsis</a>
</div>
<div class="sgc-toc-level-1">
  <a href="../Text/toc.html">Table of Contents</a>
</div>
<div class="sgc-toc-level-1">
  <a href="../Text/ch0001_26220.html">Prologue</a>
</div>
<div class="sgc-toc-level-1">
  <a href="../Text/ch0002_26223.html">Chapter One</a>
</div>
<div class="sgc-toc-level-1">
  <a href="../Text/ch0003_26620.html">Chapter Two</a>
</div>
<div class="sgc-toc-level-1">
  <a href="../Text/ch0004_26674.html">Chapter Three</a>
</div>
<div class="sgc-toc-level-1">
  <a href="../Text/ch0005_26910.html">Chapter Four</a>
</div>
<div class="sgc-toc-level-1">
  <a href="../Text/ch0006_27037.html">Chapter Five</a>
</div>
<div class="sgc-toc-level-1">
  <a href="../Text/ch0007_27245.html">Chapter Six</a>
</div>
<div class="sgc-toc-level-1">
  <a href="../Text/ch0008_27326.html">Chapter Seven</a>
</div>
<div class="sgc-toc-level-1">
  <a href="../Text/ch0009_27670.html">Chapter Eight</a>
</div>
<div class="sgc-toc-level-1">
  <a href="../Text/ch0010_27831.html">Chapter Nine</a>
</div>
<div class="sgc-toc-level-1">
  <a href="../Text/ch0011_28028.html">Chapter Ten</a>
</div>
<div class="sgc-toc-level-1">
  <a href="../Text/ch0012_28184.html">Chapter Eleven</a>
</div>
<div class="sgc-toc-level-1">
  <a href="../Text/ch0013_28466.html">Chapter Twelve</a>
</div>
</body></html>
```

**Comment by daniel-j** [comment]
Will try solve this, but I can't promise that it will work. Might be that his tool uses EPUB2 and mine EPUB3, or something with the NCX file.
Not sure what Sigil's feature does really, haven't used it before.

**Comment by Novel-Idea** [comment]
[http://www.howtomakedigitalbooks.com/blog-title/2015/9/30/yes-you-need-two-different-tables-of-contents-for-your-ebook](http://www.howtomakedigitalbooks.com/blog-title/2015/9/30/yes-you-need-two-different-tables-of-contents-for-your-ebook)

I found this resource that might help give a template for both to give a better idea.

In addition, I gathered this information from Apple's website on how they translate the data:

Source: [https://support.apple.com/en-us/HT202972](https://support.apple.com/en-us/HT202972)

EPUB 3
You can create items in the navigation document (an XHTML file) using the HTML5 <nav> element. Because each navigation item uses <nav> elements, you must include an epub:type attribute to identify the purpose of each <nav>. These structures include:
Table of contents: A table of contents is required for all books.
Landmarks: Landmarks are required for fixed-layout books if you don't provide a custom sample.
Page-list: A page-list is optional for both formats.
EPUB 2
A table of contents is created using a <navMap> element in the NCX (a .ncx file). The iBooks app uses the data in the NCX to build the table of contents, which the customer can access from the navigation bar in the iBooks app.
The navMap element contains navPoints. Each navPoint creates an entry in the table of contents. However, if the navMap contains only one navPoint, iBooks suppresses the list table of contents. This is useful if you're creating a picture book that doesn't need a list table of contents because it doesn't have chapters. iBooks will always create a thumbnail table of contents for a fixed-layout book.

I'll fiddle with this a bit in Sigil.

Did you just manually create the ToC for Pink Eyes? I remember I had no issues with that .EPUB.

**Comment by daniel-j** [comment]
Seems like iBooks on iPhone has a bug where it breaks the TOC and syncing when XHTML files are put in a subdirectory. Since I used Sigil's directory structure, fimfic2epub is affected too. Read more here: https://github.com/Sigil-Ebook/Sigil/issues/341
I am currently working on a new version of the tool that will fix this issue (finally!)

**Comment by daniel-j** [comment]
I have updated fimfic2epub to put the TOC XHTML in the OEBPS dir. iBooks on mobile seems to cache too hard, so you need to save ebooks with a new title (I have already changed the `dc:identifier` format). I do not know how to clear the cache, but other than that it seems to work nicely!

**Comment by daniel-j** [comment]
I have got confirmation from @Novel-Idea that the fix works. Finally!
