### ISSUE TITLE
Bug Report: Meta-Data "Tags" are not showing properly in iBooks.

### ISSUE THREAD

**Issue by Novel-Idea** [daniel-j/fimfic2epub#2]
After generating the .EPUB, only the first tag in the book's listing on FiMFiction appears in the meta-data when viewing the book by category in iBooks.

Upon further inspection in Sigil, this application creates separate "dc:subject" fields for each tag, while Nyergunds's Converter uses a single "dc:subject" field with each tag separated by a comma and a space.

**Comment by daniel-j** [comment]
iBooks only shows the first `dc:subject`. For now, I've added Fimfiction as a subject so all epubs generated appear in that category. There is no standard on how `dc:subject` is supposed to be used, so it is up the the eReader creators to do as they want. For example, Calibre expects multiple `dc:subject`s and most others do too. I do not know of a good solution here.

Some links about the topic:
http://blog.epubbooks.com/642/epub-creation-when-subject-matters
http://www.pigsgourdsandwikis.com/2012/02/metadata-in-ibooks-ibookstore-itunes.html

**Comment by Novel-Idea** [comment]
Perhaps you could add a checkbox in the proposed options menu for "iBooks EPUBs" that would consolidate all of the subjects into a single field, otherwise it would be set as multiple fields.

**Comment by Novel-Idea** [comment]
Issue resolved with the new addition to the options menu. Tags now are showing up properly. That being said, I think the Rating Tag (Everyone, Teen, Mature) should be auto-populated as an option. In addition, I think your original mockup with "iBooks only" was a good addition, especially since folks won't know about that detail.
