### ISSUE TITLE
Doesn’t include author’s notes

### ISSUE THREAD

**Issue by jmcken1** [daniel-j/fimfic2epub#23]
The feature to include the author’s notes in the EPUB appears to be broken. It’s not working on any of the stories I use this tool on (all of which have clear author’s notes). I tried toggling “Put all notes at the end of the ebook” to see if that changed anything, but it didn’t. Meanwhile, author’s notes are saved when using FimFic’s default EPUB download.

**Comment by Benny-** [comment]
Please list the version of the software where this bug was visible. (try to always do this when reporting issues)

You also reported [another issue](https://github.com/daniel-j/fimfic2epub/issues/22). This issue should be solved in the master branch if you checkout directly using git and use the command line to download the story. If it is still broken you can comment on the [related issue](https://github.com/daniel-j/fimfic2epub/issues/20).

Welcome to github! Nice work on reporting both issues so far. We can only solve things if they are reported.

**Comment by jmcken1** [comment]
Re: software version – Apologies for the oversight. I’m using **v1.6.3**, the latest available from the [Mozilla site](https://addons.mozilla.org/en-US/firefox/addon/fimfic2epub/). (I found it there by accident whilst searching for “EPUBReader”, and I thought I’d try it out. Has Fimfic2epub been announced anywhere else?)

More info, in case it’s relevant:
» Firefox v55.0.3 (x64)
» Can provide a list of add-ons on request (there’s a couple dozen)
» OS: Windows 8.1 Pro (x64)

I’m sorry, but I have no idea what the “master branch” is or what “checkout directly using git” means – I know zero about programming or using command line stuff (other than some basic CMD tasks in Windows, which I’m guessing isn’t what you meant). I just found this page using the “Support site” link on the Mozilla page and I saw people were posting bugs, so I wanted to add the one(s) I’d found. Apologies for any confusion.

I’m willing to follow any steps you give me, if you have the time and patience to explain them for a newbie. Otherwise, I’m happy to report any bugs I find, but my ability to help diagnose the cause will be limited.

**Comment by Benny-** [comment]
You could have installed a version and only tried and saw this bug after a new release was made. Or you could have installed a developer version from this website. That is why it is always important to list the version or git commit hash. Thank you for the additional information! Any bit of information is valuable and helps us better in tracking the bug down. Please note that I am not actively working on this issue at this moment, it has not been assigned to someone.

To download the latest developer version you don't actually need git. Go to the [project page](https://github.com/daniel-j/fimfic2epub) and hit the "Clone or download" button. Next click "Download ZIP". This will download the latest master branch. Make sure to read the Development section on the project page on how to build this development version of fimfic2epub.

You can [learn more](https://git-scm.com/) about git and branches if you'd like to contribute to this project.

Join us on [discord](https://discord.gg/nm3fAY) (1 day valid invite) for real-time chat. Say "hi" in the `#epub` channel.

**Comment by daniel-j** [comment]
Updated the Firefox extension. Should be fixed now! :)

**Comment by jmcken1** [comment]
The new update fixed everything for me! Author’s notes work, Mature-tagged stories work, and it even fixed a small glitch I hadn’t mentioned where the fimfic2epub button only worked once per page load (I had to reload the page for each story I wanted to download). All hail v1.6.5!

Thanks. This add-on is now as awesome as it should be.
