### ISSUE TITLE
Broken as of 06/30/18 (stuck at “Fetching metadata…”)

### ISSUE THREAD

**Issue by jmcken1** [daniel-j/fimfic2epub#24]
As of today, the extension doesn’t work on any fic I’ve tried it on. When I click the icon, the downloader window appears, but the progress immediately stays stuck at the first step, “Fetching metadata…”. I think they changed something under the hood at the site that caused this.

Using fimfic2epub v1.7.33
Firefox 61.0 (x64)
Windows 8.1 Pro (x64)
![image](https://user-images.githubusercontent.com/31985081/42128812-1d3707b6-7c82-11e8-80a0-913bc5c4cddc.png)

**Comment by jmcken1** [comment]
Welp, seems the issue has suddenly resolved itself within the last day or two. Exporting EPUBs now works just fine.

**Comment by daniel-j** [comment]
Yeah, Fimfiction changed something with the api, but have reverted that change now.
