### ISSUE TITLE
Fimfic 2 epub has stopped working

### ISSUE THREAD

**Issue by keybounce** [daniel-j/fimfic2epub#27]
I'm not really sure what else to say. When I select download, either by the dropdown arrow and "download as epub", or by clicking on the extension icon, nothing happens.

Browser console log:
```
e is undefined  fimfic2epub.js:86
	A/< jar:file:///Users/michael/Library/Application%20Support/Firefox/Profiles/0lyhtfoi.No%20addons/extensions/fimfic2epub@mozilla.org.xpi!/build/fimfic2epub.js:86:24352
	runSafeSyncWithoutClone resource://gre/modules/ExtensionUtils.jsm:71:14
	runSafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:133:38
	wrapPromise/</< resource://gre/modules/ExtensionCommon.jsm:322:15
	withLastError resource://gre/modules/ExtensionCommon.jsm:262:14
	wrapPromise/< resource://gre/modules/ExtensionCommon.jsm:316:11
Unchecked lastError value: Error: Please set webextensions.storage.sync.enabled to true in about:config  ExtensionCommon.jsm:265
	withLastError resource://gre/modules/ExtensionCommon.jsm:265:9
	wrapPromise/< resource://gre/modules/ExtensionCommon.jsm:316:11
uncaught exception: undefined
```

**Comment by daniel-j** [comment]
Does this happen on every story or some? Try reinstall the addon. Try Google Chrome.

**Comment by keybounce** [comment]
On 2019-07-29, at 3:15 PM, djazz <notifications@github.com> wrote:

> Does this happen on every story or some? Try reinstall the addon. Try Google Chrome.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


Every story. I did try a reinstall. ... Chrome ... let me tell you about chrome and my system ...

(look through 40 years of computer nerd music looking for something about no more ram. Swapping and swapping like it just cant wait. No more ram and no more processes spawn.)

(Ok, "No more words" was never turned into such a song, but it's a wonderful idea.)

---
Entertaining minecraft videos
http://YouTube.com/keybounce
