### ISSUE TITLE
`Internal Server Error` for fics with no cover art

### ISSUE THREAD

**Issue by 64617** [daniel-j/fimfic2epub#29]
A few (not very good) examples I tested at [your website](https://fimfiction.djazz.se/):
```
https://www.fimfiction.net/story/315940/the-duke-abides
https://www.fimfiction.net/story/453956/the-broken-treaty
https://www.fimfiction.net/story/424744/a-lightning-in-the-dark
```

I noticed you made (and closed) a similar [pull request](https://github.com/daniel-j/fimfic2epub/issues/26), but this doesn't look to be intended behavior.

Other fics work just fine.

**Comment by daniel-j** [comment]
Thanks, a native npm dependency (canvas) got a version mismatch with nodejs. I recompiled it and it now works fine. Thanks for reporting!
