### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by 64617** [daniel-j/fimfic2epub#32]
https://fimfiction.djazz.se/

Maintaining the site is probably a burden && if you're shutting it down for good, it's okay. Having a public notice about it would be nice, though.

**Comment by daniel-j** [comment]
Hi, thanks for the heads up. Seems like the service had crashed, while exporting a story (might be Kepubify related?)
This story was being converted at the time: https://www.fimfiction.net/story/310004/fallout-equestria-long-haul
This isn't an issue with fimfic2epub itself though, more in how the little server I made works: https://github.com/daniel-j/fimfic2epub-server
```
node:internal/validators:219
    throw new ERR_INVALID_CALLBACK(callback);
    ^
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at makeCallback (node:fs:184:3)
    at Object.unlink (node:fs:1238:14)
    at ChildProcess.<anonymous> (fimfic2epub-server/server/handleDownload.js:124:14)
    at Object.onceWrapper (node:events:485:26)
    at ChildProcess.emit (node:events:378:20)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
code: 'ERR_INVALID_CALLBACK'
}

```

**Comment by 64617** [comment]
That's great to hear! Apologies for my presumptuousness.

I wasn't the one to request that particular fic, if that's what you're asking.

**Comment by daniel-j** [comment]
Yeah, it looks like it crashed a few days ago and I hadn't noticed. Thanks anyway!
