### ISSUE TITLE
Chapter Headers missing and external Pictures not being downloaded in CLI Version

### ISSUE THREAD

**Issue by Princess-Luna-at** [daniel-j/fimfic2epub#39]
I noticed some weirdness lately with the CLI Version where it stopped Downloading External Pictures and only embeds the Links.
In Addition there is no Header created anymore despite the -H not being set.

commandline in my script used: `fimfic2epub -T -c -W -D -b -r -w 0 -j $link`
 Arch Linux
 Kernel: 5.12.14-zen1-1-zen
fimfic2epub 1.7.55-1
npm: 7.17.0-1
semver: 7.3.5-2
nodejs: nodejs 16.5.0-1
pango 1:1.48.6-1
libjpeg-turbo 2.1.0-1

**Comment by daniel-j** [comment]
Should be fixed now!
