### ISSUE TITLE
Bug Report: Tag Images do not show properly when using different view modes

### ISSUE THREAD

**Issue by Novel-Idea** [daniel-j/fimfic2epub#4]
The various genre tags do not show up well when using other view modes in iBooks, specifically dark ones.

Suggestion: Make them true images instead of simply text.

<img width="519" alt="screen shot 2016-08-18 at 9 08 38 am" src="https://cloud.githubusercontent.com/assets/21106478/17781394/05fde988-6524-11e6-85ed-1cae69ad8c8f.png">
<img width="501" alt="screen shot 2016-08-18 at 9 08 33 am" src="https://cloud.githubusercontent.com/assets/21106478/17781393/05fc48a8-6524-11e6-9a35-1d7237e7cad8.png">
<img width="518" alt="screen shot 2016-08-18 at 9 08 26 am" src="https://cloud.githubusercontent.com/assets/21106478/17781395/05fd7930-6524-11e6-9254-fb6f7c65c9b9.png">
<img width="488" alt="screen shot 2016-08-18 at 9 06 17 am" src="https://cloud.githubusercontent.com/assets/21106478/17781396/05fec27c-6524-11e6-85ed-e0fa9144b1d0.png">

**Comment by daniel-j** [comment]
I not only fixed the missing background color and change of text color, but also author's notes, date/character boxes and left/right side panel boxes!

I used this solution:
https://gist.github.com/adaptivegarage/aef95223fab9a39db45f

It is possible to create fully custom styling for the grey and black/night themes in the future.

**Comment by Novel-Idea** [comment]
Verified fix externally. Issue resolved.
