### ISSUE TITLE
Feature Request: Link to Chapter Comments

### ISSUE THREAD

**Issue by Novel-Idea** [daniel-j/fimfic2epub#5]
One of the cool parts about Nyerguds's converter is at the end of each chapter, there is a hyperlink that leads directly to that chapter's specific comments. This allows a reader to leave comments with a press of a button and greatly increases the likelihood of comments. I think it's especially important to have one at the end of the book. While I know there's a link at the beginning of the book, having one right at hand makes it easier (and folks tend to be lazy, let's just be honest).

**Comment by daniel-j** [comment]
Fixed in 9ad70f66b15c0f837b633f001fef49a209c4d15a
