### ISSUE TITLE
Suggestion: More Visible Integration

### ISSUE THREAD

**Issue by Novel-Idea** [daniel-j/fimfic2epub#7]
The icon that FimFiction uses for EPUB downloads is itty-bitty-tiny-whiny. If it's possible, it would be great if there was some sort of extra button allowing direct downloads while on a synopsis page (and only the synopsis page). I don't know how easily that is to add, but it would be a nice feature. 

In addition (or as an alternate idea) the button in Chrome toolbar should give you the option to create an EPUB from the page as well. As of now, it serves no purpose. 

While I realize the Bookmarklet would do a similar thing, it would be nice to have a dynamic option.

**Comment by daniel-j** [comment]
Added a pageAction to the extension, so the icon in the Chrome toolbar will now work on story pages and inside chapters!
